schemes:
  luc:
    name: LUC
    color: olive
    marker: 'o'
  cubic:
    name: TCP Cubic
    color: black
    marker: '*'
  bbr2:
    name: TCP BBR2
    color: gold
    marker: '^'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
